services:
  - type: web
    name: travelsease
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn travel_site.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: travel_site.settings
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
