# Generated by Django 5.2.4 on 2025-07-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveloption',
            options={'ordering': ['departure_datetime']},
        ),
        migrations.RenameField(
            model_name='traveloption',
            old_name='datetime',
            new_name='departure_datetime',
        ),
    ]
